export enum Icon {
    NORMAL_TYPE = "normal",
    FIRE_TYPE = "fire",
    WATER_TYPE = "water",
    GRASS_TYPE = "grass",
    ELECTRIC_TYPE = "electric",
    ICE_TYPE = "ice",
    FIGHTING_TYPE = "fighting",
    POISON_TYPE = "poison",
    GROUND_TYPE = "ground",
    FLYING_TYPE = "flying",
    PSYCHIC_TYPE = "psychic",
    BUG_TYPE = "bug",
    ROCK_TYPE = "rock",
    GHOST_TYPE = "ghost",
    DARK_TYPE = "dark",
    DRAGON_TYPE = "dragon",
    STELL_TYPE = "steel",
    FAIRY_TYPE = "fairy",
    SEARCH = "search",
    NONE = "none",
}